(define (problem block-arrangement)
  (:domain block-manipulation)
  (:objects A B C O - block)
  (:init
    (ontable A)
    (on B A)
    (ontable C)
    (ontable O)
    (clear B)
    (clear C)
    (clear O)
    (handempty)
  )
  (:goal
    (and
      (ontable A)
      (ontable B)
      (on C O)
      (on O B)
      (clear C)
    )
  )
)