import re
from ABC import ABC, abstractmethod

from src.llm_plan.utils import (
    to_snake_case,
    check_syntax,
    write_formatted,
    extract_class_code,
)
from src.llm_plan.LLM import LLM


class Agent(ABC):
    """
    This agent is a base class for all agents in the LLM plan.
    It provides common functionality such as generating code and writing files.
    """

    def __init__(self, model: LLM, task_name: str):
        self.model = model
        self.task_name = task_name.strip().capitalize()  # This is the class name: ensure at least the task name starts with a capital letter
        self.environemt_name = (
            f"Environment{self.task_name}"  # Environment.py class name
        )
        self.problem_name = f"Problem{self.task_name}"  # Problem.py class name
        self.experiment_name = to_snake_case(
            task_name
        )  # This is the experiment file name


class AgentCoder(Agent):
    """
    This agent intent is to extend the code in Problem.py,
    Environment.py, or write the file for the experiments.
    """

    def __init__(self, model: LLM, task_name: str):
        super().__init__(model, task_name)
        self.prompts = {
            "problem": (
                "{history}\nHere's a Python file that defines a class for different problems.\n\n{problem_py}.\n\n\
Extend the code with a class {problem_name} to solve the following problem:\n\
{task_description}. Just return the Python class, not the entire code."
            ),
            "environment": (
                "{history}\nHere's a Python file that defines a class for different environments.\n\n{environemt_py}.\n\n\
Extend the code with a class {environemt_name} to solve the following problem:\n\
{task_description}. Just return the Python class, not the entire code."
            ),
            "experiment": (
                "{history}\nHere's a Python file that defines the experiments to run.\n\n{problem_py}.\n\n\
Write the code with {experiment_name} to solve the following problem:\n\
{task_description}. Just return the Python class, not the entire code."
            ),
        }

        self.system_prompt = (
            "You are an expert Python coder. Your task is to extend existing Python \
code files with new classes or functions based on the provided task description. You will receive a \
history of previous interactions, the current file content, and the task description. Please ensure \
that your code is syntactically correct and follows best practices."
        )

    def code_task(self, prompt: str, history: str | None) -> str:
        # 1. Use the LLM to generate code
        result = self.model.generate_sync(self.system_prompt, prompt)

        # 2. Check if the generated code has valid syntax

        # 3. Write to the appropriate file based on the task type

        return result

    def write_file(self, file_name: str, content: str) -> None:
        """
        Write the generated code to a file.
        """
        with open(file_name, "w") as file:
            file.write(content)
        print(f"Code written to {file_name}")


class AgentRefiner(Agent):
    """This agent intent is to refine the code generated by AgentCoder."""

    def __init__(self, model: LLM, task_name: str):
        super().__init__(model, task_name)

    def code_task(self, task_description: str) -> str:
        # Use the LLM to generate code
        prompt = f"Write Python code for: {task_description}"
        result = self.model.generate_sync(prompt)
        return result
