from .LLM import LLM
from abc import ABC, abstractmethod


class Agent(ABC):
    """
    Abstract base class for agents.
    """

    @abstractmethod
    def reset(self):
        """
        Reset the agent's internal state.
        """
        pass


class LLMAgent(Agent, LLM):
    """
    An agent that uses a language model to generate actions.
    """

    def __init__(self, model):
        """
        Initialize the LLMAgent with a language model.

        Args:
            model: The language model to be used by the agent.
        """
        self.model = model

    def generate_problem(self, observation):
        """
        Generate an action based on the observation using the language model.

        Args:
            observation: The current state or observation of the environment.

        Returns:
            The action generated by the language model.
        """
        return self.model.generate_action(observation)

    def reset(self):
        """
        Reset the agent's internal state if necessary.
        """
        pass  # Implement reset logic if needed
