"""This code has been completely generated by Gemini-2.5-Pro"""

from typing import List
from src.llm_plan.environment import Environment


class ThreeSwitchesRoom(Environment):
    """
    A grid environment where three agents must simultaneously press switches
    to unlock a door.

    Attributes:
        grid_size (int): The side length of the square grid.
        visibility (int): How far each agent can observe.
        agent_names (List[str]): The names of the agents.
        orchestrator_name (str): The orchestrator's name.
        plan (List[str]): The ordered workflow plan.
    """

    def __init__(self, config: str):
        """Initialize the environment from a JSON configuration file."""
        super().__init__(config)
        self.reset()

    def reset(self, config: str | None = None):
        """Set up environment, agents, orchestrator, workflow, and plan."""
        if config:
            super().__init__(config)  # reload environment with new config

        # Environment setup
        self.grid_size = self.environment.get("init", {}).get("grid_size", 4)
        self.visibility = self.environment.get("init", {}).get("visibility", 1)

        # Agents
        self.agent_names = self.agents.get("names", [])

        # Orchestrator
        self.orchestrator_name = self.config_data.get("orchestrator", {}).get(
            "name", "Orchestrator"
        )

        # Workflow actions
        self.actions = {}
        for agent in self.agent_names:
            self.actions[agent] = self.workflow.get(agent, {})

        self.actions[self.orchestrator_name] = self.workflow.get(
            self.orchestrator_name, {}
        )

        # Collect all workflow steps
        actions = []
        for agent, cfg in self.workflow.items():
            if agent == "constraints":
                continue
            actions.extend(
                ["{}.{}".format(agent, a) for a in self.workflow.get(agent, {}).keys()]
            )

        # Constraints
        self.workflow_constraints: List[str] = self.workflow.get("constraints", [])

        # Build dependency graph (schedule)
        self.plan = self.schedule(actions, self.workflow_constraints)

    def render(self):
        """Prints a human-readable representation of the environment."""
        print(f"Grid: {self.grid_size}x{self.grid_size}, visibility={self.visibility}")
        print("Agents:", ", ".join(self.agent_names))
        print("Workflow Plan:", " -> ".join(self.plan))
