"""This code has been completely generated by ChatGPT"""

from typing import List
from src.llm_plan.environment import Environment


class TwoAgentsBlocksWorld(Environment):
    """
    A Blocksworld environment with two agents:
    - AgentVowels can move blocks starting with vowels (A, E, I, O, U).
    - AgentConsonants can move blocks starting with consonants.

    Agents cannot hold more than one block at a time and must collaborate
    to reach the target configuration.
    """

    def __init__(self, config: str):
        """Initialize the environment from a JSON configuration file."""
        super().__init__(config)
        self.reset()

    def reset(self, config: str | None = None):
        """Set up environment, agents, orchestrator, workflow, and plan."""
        if config:
            super().__init__(config)

        # Environment setup
        self.blocks = self.environment.get("init", {}).get("blocks", [])
        self.positions = self.environment.get("init", {}).get("positions", {})
        self.goal_positions = self.environment.get("init", {}).get("goal_positions", {})

        # Agents
        self.agent_names = self.agents.get("names", [])

        # Orchestrator
        self.orchestrator_name = self.config_data.get("orchestrator", {}).get(
            "name", "Orchestrator"
        )

        # Workflow actions
        self.actions = {}
        for agent in self.agent_names:
            self.actions[agent] = self.workflow.get(agent, {})

        self.actions[self.orchestrator_name] = self.workflow.get(
            self.orchestrator_name, {}
        )

        # Collect all workflow steps
        actions = []
        for agent, cfg in self.workflow.items():
            if agent == "constraints":
                continue
            actions.extend(
                ["{}.{}".format(agent, a) for a in self.workflow.get(agent, {}).keys()]
            )

        # Constraints
        self.workflow_constraints: List[str] = self.workflow.get("constraints", [])

        # Build dependency graph (schedule)
        self.plan = self.schedule(actions, self.workflow_constraints)

    def render(self):
        """Prints a human-readable representation of the environment."""
        print("Blocks:", self.blocks)
        print("Initial positions:", self.positions)
        print("Goal positions:", self.goal_positions)
        print("Agents:", ", ".join(self.agent_names))
        print("Workflow Plan:", " -> ".join(self.plan))
